spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:mysql://localhost:3307/order_platform
    username: order_user
    password: order_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8082

management:
  server:
    port: 9082
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.mihaela.orderplatform: DEBUG
